/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Virtualpianos;


import sun.audio.*;
import java.io.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Yash Rangarajan
 */
public class VirtualPiano extends javax.swing.JFrame {

    /**
     * Creates new form VirtualPiano
     */
    public VirtualPiano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        jP = new javax.swing.JPanel();
        jBCs = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBDs = new javax.swing.JButton();
        jBE = new javax.swing.JButton();
        jBC = new javax.swing.JButton();
        jBD = new javax.swing.JButton();
        jBFs = new javax.swing.JButton();
        jBF = new javax.swing.JButton();
        jBGs = new javax.swing.JButton();
        jBG = new javax.swing.JButton();
        jBBf = new javax.swing.JButton();
        jBA = new javax.swing.JButton();
        jBB = new javax.swing.JButton();
        jBC5 = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jP.setBackground(new java.awt.Color(0, 0, 0));
        jP.setLayout(null);

        jBCs.setBackground(java.awt.Color.black);
        jBCs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBCs.setForeground(new java.awt.Color(255, 255, 255));
        jBCs.setText("C#");
        jBCs.setToolTipText("");
        jBCs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jBCs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBCs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCsActionPerformed(evt);
            }
        });
        jP.add(jBCs);
        jBCs.setBounds(40, 130, 50, 130);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Virtual Piano");
        jP.add(jLabel1);
        jLabel1.setBounds(20, 30, 440, 70);

        jBDs.setBackground(java.awt.Color.black);
        jBDs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBDs.setForeground(new java.awt.Color(255, 255, 255));
        jBDs.setText("D#");
        jBDs.setToolTipText("");
        jBDs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jBDs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDsActionPerformed(evt);
            }
        });
        jP.add(jBDs);
        jBDs.setBounds(100, 130, 50, 130);

        jBE.setBackground(java.awt.Color.white);
        jBE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBE.setText("E");
        jBE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBE.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEActionPerformed(evt);
            }
        });
        jP.add(jBE);
        jBE.setBounds(130, 130, 50, 240);

        jBC.setBackground(java.awt.Color.white);
        jBC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBC.setText("C");
        jBC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBC.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCActionPerformed(evt);
            }
        });
        jP.add(jBC);
        jBC.setBounds(10, 130, 50, 240);

        jBD.setBackground(java.awt.Color.white);
        jBD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBD.setText("D");
        jBD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBD.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDActionPerformed(evt);
            }
        });
        jP.add(jBD);
        jBD.setBounds(70, 130, 50, 240);

        jBFs.setBackground(java.awt.Color.black);
        jBFs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBFs.setForeground(new java.awt.Color(255, 255, 255));
        jBFs.setText("F#");
        jBFs.setToolTipText("");
        jBFs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jBFs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBFs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFsActionPerformed(evt);
            }
        });
        jP.add(jBFs);
        jBFs.setBounds(230, 130, 50, 130);

        jBF.setBackground(java.awt.Color.white);
        jBF.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBF.setText("F");
        jBF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBF.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFActionPerformed(evt);
            }
        });
        jP.add(jBF);
        jBF.setBounds(190, 130, 60, 240);

        jBGs.setBackground(java.awt.Color.black);
        jBGs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBGs.setForeground(new java.awt.Color(255, 255, 255));
        jBGs.setText("G#");
        jBGs.setToolTipText("");
        jBGs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jBGs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBGs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGsActionPerformed(evt);
            }
        });
        jP.add(jBGs);
        jBGs.setBounds(290, 130, 50, 130);

        jBG.setBackground(java.awt.Color.white);
        jBG.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBG.setText("G");
        jBG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBG.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGActionPerformed(evt);
            }
        });
        jP.add(jBG);
        jBG.setBounds(260, 130, 50, 240);

        jBBf.setBackground(java.awt.Color.black);
        jBBf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBBf.setForeground(new java.awt.Color(255, 255, 255));
        jBBf.setText("B f");
        jBBf.setToolTipText("");
        jBBf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jBBf.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBBf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBfActionPerformed(evt);
            }
        });
        jP.add(jBBf);
        jBBf.setBounds(350, 130, 50, 130);

        jBA.setBackground(java.awt.Color.white);
        jBA.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBA.setText("A");
        jBA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBA.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jP.add(jBA);
        jBA.setBounds(320, 130, 50, 240);

        jBB.setBackground(java.awt.Color.white);
        jBB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBB.setText("B");
        jBB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBB.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBActionPerformed(evt);
            }
        });
        jP.add(jBB);
        jBB.setBounds(380, 130, 50, 240);

        jBC5.setBackground(java.awt.Color.white);
        jBC5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBC5.setText("C");
        jBC5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBC5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBC5ActionPerformed(evt);
            }
        });
        jP.add(jBC5);
        jBC5.setBounds(440, 130, 60, 240);

        getContentPane().add(jP);
        jP.setBounds(20, 20, 520, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEActionPerformed
        InputStream iAudio;
        
        try{
        iAudio = new FileInputStream(new File("C:\\Music_Notes\\E.wav") );
        AudioStream iMusic = new AudioStream(iAudio);
        AudioPlayer.player.start(iMusic);
        }
        catch(IOException e){
        JOptionPane.showMessageDialog(null,e);
        }
    
     
        
    }//GEN-LAST:event_jBEActionPerformed

    private void jBCsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCsActionPerformed
        InputStream iAudio;
        
        try{
        iAudio = new FileInputStream(new File("C:\\Music_Notes\\C_sharp.wav") );
        AudioStream iMusic = new AudioStream(iAudio);
        AudioPlayer.player.start(iMusic);
        }
        catch(IOException e){
        JOptionPane.showMessageDialog(null,e);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jBCsActionPerformed

    private void jBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCActionPerformed
                InputStream iAudio;
        
        try{
        iAudio = new FileInputStream(new File("C:\\Music_Notes\\C.wav") );
        AudioStream iMusic = new AudioStream(iAudio);
        AudioPlayer.player.start(iMusic);
        }
        catch(IOException e){
        JOptionPane.showMessageDialog(null,e);
        }//// TODO add your handling code here:
    }//GEN-LAST:event_jBCActionPerformed

    private void jBDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDsActionPerformed
         InputStream iAudio;
        
        try{
        iAudio = new FileInputStream(new File("C:\\Music_Notes\\E_flat.wav") );
        AudioStream iMusic = new AudioStream(iAudio);
        AudioPlayer.player.start(iMusic);
        }
        catch(IOException e){
        JOptionPane.showMessageDialog(null,e);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jBDsActionPerformed

    private void jBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDActionPerformed
       InputStream iAudio;
        
        try{
        iAudio = new FileInputStream(new File("C:\\Music_Notes\\D.wav") );
        AudioStream iMusic = new AudioStream(iAudio);
        AudioPlayer.player.start(iMusic);
        }
        catch(IOException e){
        JOptionPane.showMessageDialog(null,e);
        } // TODO add your handling code here:
    }//GEN-LAST:event_jBDActionPerformed

    private void jBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFActionPerformed
        InputStream iAudio;
        
        try{
        iAudio = new FileInputStream(new File("C:\\Music_Notes\\F.wav") );
        AudioStream iMusic = new AudioStream(iAudio);
        AudioPlayer.player.start(iMusic);
        }
        catch(IOException e){
        JOptionPane.showMessageDialog(null,e);
        } // TODO add your handling code here:
    }//GEN-LAST:event_jBFActionPerformed

    private void jBFsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFsActionPerformed
        InputStream iAudio;
        
        try{
        iAudio = new FileInputStream(new File("C:\\Music_Notes\\F_sharp.wav") );
        AudioStream iMusic = new AudioStream(iAudio);
        AudioPlayer.player.start(iMusic);
        }
        catch(IOException e){
        JOptionPane.showMessageDialog(null,e);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jBFsActionPerformed

    private void jBGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGActionPerformed
        InputStream iAudio;
        
        try{
        iAudio = new FileInputStream(new File("C:\\Music_Notes\\G.wav") );
        AudioStream iMusic = new AudioStream(iAudio);
        AudioPlayer.player.start(iMusic);
        }
        catch(IOException e){
        JOptionPane.showMessageDialog(null,e);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jBGActionPerformed

    private void jBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAActionPerformed
        InputStream iAudio;
        
        try{
        iAudio = new FileInputStream(new File("C:\\Music_Notes\\A.wav") );
        AudioStream iMusic = new AudioStream(iAudio);
        AudioPlayer.player.start(iMusic);
        }
        catch(IOException e){
        JOptionPane.showMessageDialog(null,e);
        } // TODO add your handling code here:
    }//GEN-LAST:event_jBAActionPerformed

    private void jBGsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGsActionPerformed
       InputStream iAudio;
        
        try{
        iAudio = new FileInputStream(new File("C:\\Music_Notes\\G_sharp.wav") );
        AudioStream iMusic = new AudioStream(iAudio);
        AudioPlayer.player.start(iMusic);
        }
        catch(IOException e){
        JOptionPane.showMessageDialog(null,e);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jBGsActionPerformed

    private void jBBfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBfActionPerformed
        InputStream iAudio;
        
        try{
        iAudio = new FileInputStream(new File("C:\\Music_Notes\\B_flat.wav") );
        AudioStream iMusic = new AudioStream(iAudio);
        AudioPlayer.player.start(iMusic);
        }
        catch(IOException e){
        JOptionPane.showMessageDialog(null,e);
        } // TODO add your handling code here:
    }//GEN-LAST:event_jBBfActionPerformed

    private void jBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBActionPerformed
         InputStream iAudio;
        
        try{
        iAudio = new FileInputStream(new File("C:\\Music_Notes\\B.wav") );
        AudioStream iMusic = new AudioStream(iAudio);
        AudioPlayer.player.start(iMusic);
        }
        catch(IOException e){
        JOptionPane.showMessageDialog(null,e);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jBBActionPerformed

    private void jBC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBC5ActionPerformed
         InputStream iAudio;
        
        try{
        iAudio = new FileInputStream(new File("C:\\Music_Notes\\C5.wav") );
        AudioStream iMusic = new AudioStream(iAudio);
        AudioPlayer.player.start(iMusic);
        }
        catch(IOException e){
        JOptionPane.showMessageDialog(null,e);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jBC5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VirtualPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VirtualPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VirtualPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VirtualPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VirtualPiano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBA;
    private javax.swing.JButton jBB;
    private javax.swing.JButton jBBf;
    private javax.swing.JButton jBC;
    private javax.swing.JButton jBC5;
    private javax.swing.JButton jBCs;
    private javax.swing.JButton jBD;
    private javax.swing.JButton jBDs;
    private javax.swing.JButton jBE;
    private javax.swing.JButton jBF;
    private javax.swing.JButton jBFs;
    private javax.swing.JButton jBG;
    private javax.swing.JButton jBGs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jP;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
